// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThreeL.Blob.Clients.Win;

#nullable disable

namespace ThreeL.Blob.Clients.Win.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231024063147_AddUploadingFinishTime")]
    partial class AddUploadingFinishTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("ThreeL.Blob.Clients.Win.Entities.UploadFileRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TransferBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadFinishTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UploadFileRecords");
                });

            modelBuilder.Entity("ThreeL.Blob.Clients.Win.Entities.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DaliyUploadMaxSizeLimit")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DownloadSpeedLimit")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaxSpaceSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TodayUploadMaxSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UploadMaxSizeLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
